CRUD - Task
jihaneH/TodoList pull request #2
Opened 2022-01-11 14:32 UTC by jihaneH

### CRUD - Task

- Remove all hardcoded items from the tasks array

2022-01-13 07:40 UTC, brytebee requested changes
Hi, @ 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- awesome readme✔️
- clean code✔️
- properly organized your code into modules✔️
- no console errors✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 07:40 UTC, brytebee commented on src/index.js
> +});
- [ ] **Required:** You have accurately implemented an add event using the enter button 👏👏. However, it would also be nice if the ➕ icon on your UI can be clicked to achieve the same result as well. Let's implement an **add functionality** when the ➕ icon is clicked.

2022-01-13 08:53 UTC, jihaneH commented on src/index.js
> +});
Thank you, It's done

2022-01-13 09:24 UTC, hiromataba approved these changes
# Status: Approved :tada:  :champagne:  :confetti_ball: 
Hi @jihaneH        :wave: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your README file looks very professional :+1: 
- You have a good design :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 09:36 UTC, merged

2022-01-28 21:21 UTC, jihaneH commented
@hiromataba @brytebee 
![icegif-1433](https://user-images.githubusercontent.com/7243132/151623082-9fbf0ac1-2379-48fc-b116-68d9bb8bba30.gif)